export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_TIME_SCHEDULE_CONFIGURATION =
  "FETCH_TIME_SCHEDULE_CONFIGURATION";
export const STORE_TIME_SCHEDULE_CONFIGURATION =
  "STORE_TIME_SCHEDULE_CONFIGURATION";
export const FETCH_TIME_SCHEDULE = "FETCH_TIME_SCHEDULE";
export const STORE_TIME_SCHEDULE = "STORE_TIME_SCHEDULE";
export const FEATCH_BUS_SCHEDULE = "FEATCH_BUS_SCHEDULE";
export const STORE_BUS_SCHEDULE = "STORE_BUS_SCHEDULE";
export const FETCH_SHOW_MOVIE = "FETCH_SHOW_MOVIE";